project:
  type: website

website:
  title: "Computational Social Science for Sustainability (EBS 182/282)"
  navbar:
    right:
      - href: index.qmd
        text: Course information and syllabus

      - href: book.qmd
        text: Book

      - href: bibliography.qmd
        text: References

      - href: lectures.qmd
        text: Lectures

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



