project:
  type: website

website:
  title: "Computational Social Science for Sustainability (EBS 182/282)"
  navbar:
    background: "#8C1515"
    foreground: "#FFFFFF"
    right:
      - href: index.qmd
        text: Course information and syllabus

      - href: book/index.qmd
        text: Book

      - href: bibliography/index.qmd
        text: Bibliography

      - href: lectures/index.qmd
        text: Lectures

      - href: labs/index.qmd
        text: "Lab exercises"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


bibliography: /users/mt/workspace/Writing/library.bib
